---
title: "predictions"
author: "Lauren Jenkins"
date: "5 January 2021"
output: html_document
---

Setup
```{r, include = F}
rm(list = ls())
library(dplyr)
library(ggplot2)
library(tidyr)

library(raster)
library(rgdal)
library(enmSdm)
library(terra)
library(maxnet)
library(sf)

library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)

setwd('/Volumes/LJ MacBook Backup/MOBOT/PVMvsENM')
```

```{r}
fileName <- list.files(path = './predictions/',
                         pattern = '.tif',
                         full.names = T)
Frax_Amer <- stack(fileName[1])
names(Frax_Amer) <- paste0('Frax_Amer_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Amer)
```

```{r}
Frax_Caro <- stack(fileName[2])
names(Frax_Caro) <- paste0('Frax_Caro_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Caro)
```

```{r}
Frax_Cusp <- stack(fileName[3])
names(Frax_Cusp) <- paste0('Frax_Cusp_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Cusp)
```

```{r}
Frax_Greg <- stack(fileName[4])
names(Frax_Greg) <- paste0('Frax_Greg_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Greg)
```

```{r}
Frax_Nigr <- stack(fileName[5])
names(Frax_Nigr) <- paste0('Frax_Nigr_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Nigr)
```

```{r}
Frax_Penn <- stack(fileName[6])
names(Frax_Penn) <- paste0('Frax_Penn_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Penn)
```

```{r}
Frax_Prof <- stack(fileName[7])
names(Frax_Prof) <- paste0('Frax_Prof_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Prof)
```

```{r}
Frax_Quad <- stack(fileName[8])
names(Frax_Quad) <- paste0('Frax_Quad_', seq(21000, 0, by=-1000), 'ybp')
plot(Frax_Quad)
```

Combining rasters:
```{r}
climYears <- seq(21000, 0, by=-1000)
tmp <- list(brick(fileName[[1]]), brick(fileName[[2]]), brick(fileName[[3]]), 
             brick(fileName[[4]]), brick(fileName[[5]]), brick(fileName[[6]]), 
             brick(fileName[[7]]), brick(fileName[[8]]))
meansList <- list()
maxList <- list()
for (i in 1:length(climYears)) {
  climYear <- climYears[i]
  n <- stack(tmp[[1]][[i]], tmp[[2]][[i]], tmp[[3]][[i]], tmp[[4]][[i]], 
             tmp[[5]][[i]], tmp[[6]][[i]], tmp[[7]][[i]], tmp[[8]][[i]])
  mn <- raster::mosaic(n[[1]], n[[2]], n[[3]], n[[4]], n[[5]], n[[6]], 
                         n[[7]], n[[8]], fun = mean)
  names(mn) <- paste0(climYear, ' ybp')
  meansList <- append(meansList, mn)
  
  mx <- raster::mosaic(n[[1]], n[[2]], n[[3]], n[[4]], n[[5]], n[[6]], 
                        n[[7]], n[[8]], fun = max)
  names(mx) <- paste0(climYear, ' ybp')
  maxList <- append(maxList, mx)
  
}
```

ENM Means:
```{r}
plot(stack(meansList))
```

ENM Max:
```{r}
plot(stack(maxList))
```

Pollen rasters:
```{r}
fileName <- '/Volumes/GoogleDrive/.shortcut-targets-by-id/0ByjNJEf91IW5SUlEOUJFVGN0Y28/NSF_ABI_2018_2021/data_and_analyses/pg_pollen/matern_overdispersed/predictions-FRAXINUS_meanpred.tif'
pollenRast <- brick(fileName)
names(pollenRast) <- paste0('Pollen_', seq(21000, 0, by=-1000), 'ybp')
plot(pollenRast)
```


