---
title: "Loading all models"
author: "Lauren Jenkins"
date: "17 December 2021"
output: html_document
---

Set up environment.
```{r, include = FALSE}
rm(list = ls())
setwd('/Volumes/lj_mac_22/MOBOT/PVMvsENM')
knitr::opts_knit$set(root.dir = '/Volumes/lj_mac_22/MOBOT/PVMvsENM')
library(dplyr)
library(ggplot2)
library(tidyr)

library(raster)
library(rgdal)
library(enmSdm)
library(terra)
library(maxnet)
library(sf)

library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)

# set constants
pc <- 5
gcm <- 'Lorenz_ccsm'
```

Fraxinus americana
```{r}
speciesAb_ <- 'Frax_Amer'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus americana '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus anomala
```{r}
speciesAb_ <- 'Frax_Anom'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus anomala '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus caroliniana
```{r}
speciesAb_ <- 'Frax_Caro'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus caroliniana '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus cuspidata

** Check values in E Texas.
plot(raster)
extract(raster, click(n=1))
```{r}
speciesAb_ <- 'Frax_Cusp'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus cuspidata '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus greggii
```{r}
speciesAb_ <- 'Frax_Greg'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus greggii '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus latifolia
```{r}
speciesAb_ <- 'Frax_Lati'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus latifolia '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus nigra
```{r}
speciesAb_ <- 'Frax_Nigr'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus nigra '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus pennsylvanica
```{r}
speciesAb_ <- 'Frax_Penn'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus pennsylvanica '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus profunda
```{r}
speciesAb_ <- 'Frax_Prof'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus profunda '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```

Fraxinus quadrangulata
```{r}
speciesAb_ <- 'Frax_Quad'
load(paste0('./workspaces/05 - Modeling Workspace - ', speciesAb_, 
                  ' Model Output - PC', pc, '_GCM_', gcm))
plot(rangeMap, border = 'blue', main = substitute(paste('Maxent output, ', 
                                                        italic('Fraxinus quadrangulata '),
                                                        'occurrences')), 
     sub = paste0('buffer = ', buffer_distance, ' km'))
plot(envMap, add = TRUE)
plot(rangeMap, border = 'blue', add = TRUE)
map("state", add = TRUE)
map("world", add = TRUE)
points(records$longitude, records$latitude, pch = 16, cex = 0.6, col = 'red')
```
